### ISSUE TITLE
Add support for geckodriver log

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-selenium#108]
I would like to get the geckodriver log when there is a geckodriver related failure, and have it added to the html report.

I can work on this but would need a little mentoring.

**Comment by davehunt** [comment]
Thanks for raising this @jrbenny35, I agree it would be a valuable addition. By default the geckodriver log file is named geckodriver.log and written to the current working directory, which is useful for anyone running locally wanting to check the contents. I think there are a couple of options:

1. Attempt to locate geckodriver.log when enhancing the HTML report. If we find it, we can add it to the report. The problem with this is that it makes some assumptions on the log file name and location is specific to Firefox/geckodriver.

2. We could explicitly tell Selenium where to write the log file, and store this in the pytest configuration object. Then, when we enhance the HTML report we just look for this attribute in the configuration object and if found we can add the log.

I'd say let's go for option 2. First, we'd want to add `log_path` as a driver keyword argument in [this fixture](https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/drivers/firefox.py#L34-L41). I don't think we need to create a `driver_log` fixture, but that's also an option. For the value we should use 'geckodriver.log' in the working directory, so that there's no unexpected changes from the current behaviour. We should then be able to store this as `pytestconfig._driver_log` (you'll need to add the `pytestconfig` fixture to the argument list). Then, when [gathering logs](https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/pytest_selenium.py#L200-L217) for the HTML report, we should append the file located at `item.config._driver_log` if it's present. This approach means we should easily be able to add support for other drivers that allow users to specify a log location.

Let me know if you have any questions.

**Comment by jrbenny35** [comment]
The function ```pytest_runtest_makereport``` is what generates the HTML?

**Comment by davehunt** [comment]
Nope, the [pytest-html](https://pypi.python.org/pypi/pytest-html) plugin generates the HTML. The `pytest_runtest_makereport` hook just adds stuff to `report.extra` to be picked up by the other plugin.

**Comment by jrbenny35** [comment]
Trying to run a test of this command and I keep running into this error

```selenium.common.exceptions.WebDriverException: Message: GET /session/729f9e4e-b687-2445-91bb-1368f159748e/log/types did not match a known command```

It seems something is trying to map a selenium request as a log type.

**Comment by davehunt** [comment]
That's known and should be safely ignored. It's because retrieving logs isn't in the WebDriver spec, so it fails with geckodriver. For this patch, you shouldn't need to worry about the remote command.

**Comment by jrbenny35** [comment]
So this ```return``` isn't exiting the ```_gather_logs``` function?

https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/pytest_selenium.py#L206

**Comment by davehunt** [comment]
Yes, it is. You'd need to ensure the new code isn't affected by the exception.

**Comment by davehunt** [comment]
Fixed by #109
