### ISSUE TITLE
Save screenshot to tempfile in text mode

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest-selenium#133]
Screenshots are really valuable tools for debugging selenium test (even more so when running in headless Firefox or Chrome). Currently, pytest-selenium injects screenshots into HTML reports, but maybe it could also save those screenshots to the disk and give the file path in the text summary, possibly optionally? At the moment it generates a (base64) screenshot in every case and just drops it when `html` is not enabled.

**Comment by ramonasuciu** [comment]
I was able to save the screenshots to disk, using Selenium's save_screenshot(file_path).
You can rename the files as you wish and move them to a separate folder. I left them in assets, for convenience purposes, but the idea is that, using save_screenshot(file_path), you are able to keep the screenshots locally. Also, you can inject them still in pytest's html report. 

Hope it helps.

**Comment by xmo-odoo** [comment]
@ramonasuciu yeah you can take them manually without issues, but it's less convenient than pytest-selenium doing so on only failures, which as far as I can see it already does *but* it drops the screenshot if not using HTML reports.

**Comment by ramonasuciu** [comment]
@xmo-odoo what I meant is that pytest-html still picks the screenshots which are now created as png files, not as base64, and attaches them to the corresponding failing scenario in the html report.
The only difference is that I am now saving the screenshots as files per-say, in any location, and instruct pytest to pick them up from that new location, in order to properly attach them to the html report.

Please let me know if you'd need more details on how I've done this.

Thanks,
Ramona

**Comment by BeyondEvil** [comment]
@davehunt What if were to, in the case of pytest-html not being enabled, drop the files to disk and put the file path in the summary? Either per default or per the command line/ini-setting.

ping @xmo-odoo

**Comment by xmo-odoo** [comment]
@BeyondEvil that's pretty much my original suggestion.

**Comment by BeyondEvil** [comment]
@xmo-odoo Yes :)

The problem I can see with dumping the file being the default, is littering the filesystem with screenshots.

**Comment by davehunt** [comment]
It would be fairly simple for you to do this yourself in a `conftest.py` by implementing the `pytest_runtest_makereport` hook, however I do see your point that pytest-selenium already gathers the screenshots, and just discards them if pytest-html is not available. I'd support a pull request that only grabs a screenshot when pytest-html is available, or a pull request that saves the screenshots to a temporary path. Doing the latter will need to have some way to associate the tests with the screenshots, perhaps using the test identifier to create a subdirectory in the temporary location. Rather than list all of these in the summary, I would suggest only mentioning the parent directory. Something like `/path/to/temp/screenshots/test_foo/xxx.png`

**Comment by nicoddemus** [comment]
> Doing the latter will need to have some way to associate the tests with the screenshots, perhaps using the test identifier to create a subdirectory in the temporary location.

That's a good solution, but perhaps using the `tmpdir` fixture to do the heavy lifting?

**Comment by BeyondEvil** [comment]
@nicoddemus But doesn't the tmpdir "system" do some form of cleanup right before pytest is finished? I was trying to find out, but got lost in the code...

**Comment by nicoddemus** [comment]
Yes it does, but only after 3 attempts it seems

**Comment by davehunt** [comment]
Agreed, I'd use `tmpdir` if we can (from the context of a hook).

**Comment by BeyondEvil** [comment]
@davehunt But.. but.. wouldn't pytest delete the file then when it's done? 

Or did I misinterpret @nicoddemus ?

**Comment by davehunt** [comment]
I understood that pytest preserves the temporary directories for the last three runs.

**Comment by BeyondEvil** [comment]
How can I access the `tmpdir` fixture in this function? 🤔 
https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L240
@davehunt @nicoddemus

**Comment by davehunt** [comment]
I'm not entirely sure that you can, but perhaps @nicoddemus has a suggestion..?
