### ISSUE TITLE
Unable to create session

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest-selenium#156]
Hi, I am running my test in both local and remote way, but I hit error when running remote test while local test is not happen.

![image](https://user-images.githubusercontent.com/1460421/37319987-8969fffa-26ac-11e8-8628-619cbcad2090.png)

![image](https://user-images.githubusercontent.com/1460421/37320018-b1ec9776-26ac-11e8-8f0c-db42b213ee85.png)

I have update to latest chrome driver (happened to gecko driver as well), latest selenium python binding, and selenium standalone server - 3.11.0

I have tried google my for sometimes but no solution for me now. Is this a bug on selenium itself?

**Comment by davehunt** [comment]
Please provide your full traceback, rather than screenshots from your console and the HTML report. Have you had these issues since upgrading any particular component, or have you been unable to get any tests to run? Do you have a Selenium server running at 192.168.56.102? Can you include any logs from the server?

**Comment by rarelam** [comment]
Hi

I have selenium server running at 192.168.56.102.  This is the first time I am running test with remote selenium server, and I have updated both required package, thus I have no idea which component are causing this issue.

The test simply not running on 192.168.56.102. Which log I should collect for you to investigate? I will check my selenium server console if it able to tell me something and I will post here if got any. Thanks

**Comment by davehunt** [comment]
It would still be useful to see a full traceback from your console. The one in the screenshot is cropped and potentially missing valuable information. It looks like the remote server is responding that it's unable to create the session. The console logs from the server would be valuable. I suspect your issue is not related to the plugin, but without more information it's hard to know for sure.

**Comment by rarelam** [comment]
Hi, 

Sorry for the disturb for long time.

I have restart all of my guest and host machines. And rerun the same command again. And now my test is running successfully without any error.

I didn't do anything extra and I don't have any idea what it is not working 2 days ago while it is working now.

I'll close this issue for now. Thank you for your time.

**Comment by davehunt** [comment]
Thanks for the update, I'm glad you got it working! 🎉
