### ISSUE TITLE
Please add support for retrying driver initialization

### ISSUE THREAD

**Issue by DanaSilerRhiza** [pytest-dev/pytest-selenium#219]
One of our build environments is having an intermittent problem where the pytest-selenium driver fixture fails due to a problem with bringing up Chrome (the error during the call to the driver fixture is a 104 - 'Connection reset by peer').

Granted, we want to get to the bottom of the intermittent initialization problem, but it would be awfully nice if we had a way to specify a number of retry attempts to make when initializing the driver. This would prevent intermittent test failures due to a problem that is not related to the code under test. 

I have worked around the lack of support for this behavior by copy/pasting the driver fixture code here: https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L180 into my own method. Then, I created a new fixture which has the retry logic that I want and which calls the copy/pasted pytest_selenium driver code. 

I anticipate that this solution would work for our team for a while, but I have concerns that it might break when pytest-selenium is updated. Also, other users of the pytest-selenium community might find this retry functionality useful. 

Here is my workaround for the lack of a retry at the pytest-selenium fixture level:

```   
     # Initialize the webdriver and catch any errors.
     #
     # This code came from the pytest_selenium module's driver method.
     # This method is responsible for initializing the driver. I would prefer
     # to call this method directly, but since the method is a fixture, I cannot
     # do so. The original code can be found here:
     # https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L181
     #
     # The initialization of the webdriver code and browser happens in the call to
     # driver_class(**driver_kwargs). The rest of the code was copied here verbatim
     # to ensure correct initialization of the returned driver.
     #
   
    def my_driver(self, request, driver_class, driver_kwargs):
        """Returns a WebDriver instance based on options and capabilities"""
        driver = driver_class(**driver_kwargs)
        
        event_listener = request.config.getoption("event_listener")
        if event_listener is not None:
            # Import the specified event listener and wrap the driver instance
            mod_name, class_name = event_listener.rsplit(".", 1)
            mod = __import__(mod_name, fromlist=[class_name])
            event_listener = getattr(mod, class_name)
            if not isinstance(driver, EventFiringWebDriver):
                driver = EventFiringWebDriver(driver, event_listener())

        request.node._driver = driver
        return driver

    @pytest.fixture(autouse=True, scope='function')
    def init_driver(self, request, driver_class, driver_kwargs):
        """
        Put the selenium pytest fixture on the instance of this test. 
        """
        success = False
        retries = 3
        self.driver = None

        while success != True and retries > 0:
            retries -= 1
            try:
                self.driver = self.my_driver(request, driver_class, driver_kwargs)
                success = True
            except Exception as ex:
                if retries > 0:
                    time.sleep(5)
                    if self.driver is not None:
                        self.driver.quit()
                        print('driver.quit() succeeded')
                    else:
                        print('driver initialize did not happen at all.')
                else:
                    raise ex

        yield self.driver
        self.driver.quit()
```

Here are the versions of code we are running:
-  Google Chrome 72.0.3626.81
- pytest - 4.2.0
- Python 3.6.7
- ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5)

Is this intermittent driver failure a known issue? Are there any other known workarounds? Would adding the retry logic to the main driver code make sense? Thanks!

**Comment by BeyondEvil** [comment]
Hi @DanaSilerRhiza !

Thanks for reporting this!

> Is this intermittent driver failure a known issue? 

It might be, see [here](https://github.com/SeleniumHQ/selenium/issues/6438).

> Are there any other known workarounds?

Not that I'm aware of.

> Would adding the retry logic to the main driver code make sense?

I'm reluctant to add such things to the plugin. For a couple of reasons.

- It doesn't seem to be a common issue.
- It will make the plugin more complex and harder to maintain.
- I think a simple "retry"-decorator could help out.
 
With that said, I'm happy to have other maintainers chime in. :)

**Comment by Dude-X** [comment]
@BeyondEvil I think adding a retry option is a good idea. The framework I maintain at work uses a lot more retries in some areas.

The reasons why are:
* Novice users of the framework can simply configure the number of retries without knowing how to override pytest fixtures or writing their own retry algorithms.
* Distributed systems basically demand retries since failure can happen anywhere/anytime.
* Helps prevent failed CI builds and not waste a teams time in failure analysis.
* Driver authors can introduce bugs that increase flakiness. _stares at Google_
* Make it easier for everyone to configure retry without having to invest time looking at the code and implementing it yourself, even if you do know how to write pytest plugins.

**Comment by BeyondEvil** [comment]
@Dude-X 

Good points and I agree with all of them. We also have a lot of retry-functionality in use at work.

However, I would then suggest that this functionality be added to the python-bindings instead. To me it makes sense to have it as close as possible to the "offending" code. It would also then benefit all (python) selenium users, not only the pytest ones.

A counter argument would be that the bindings should be viewed upon more as an API and should stay true as much as possible to the spec.

 Thoughts @AutomatedTester ?

**Comment by Dude-X** [comment]
With the latest Python binding using urllib3, the default for that library is to set a retry of2-3 attempts. But I made sure to expose a hook to change the retry, and set a default of 0 so that the user can control the retries. This will prevent weird things from happening. 

The thing is I have no idea what happens if you retry on communication between the client and driver, which is why made that 0. I want the user to be able to retry an action from a higher scope with the guarantee that the action will happen only once.

In the past, using Java, I had a URL that i opened with the driver that did a long running database process. Because the Java client had retry, it would run twice and slow down our test server. So I am in favor of 0 retries in the client, and let the user handle retries at a higher scope.

**Comment by BeyondEvil** [comment]
The "user" in this case being pytest-selenium?

I briefly tried decorating a fixture with a simply retry function. But couldn't get it to work. I guess we would have to deal with it inside the fixture function itself in that case.

**Comment by Dude-X** [comment]
The user should implement their own retry either with their own custom code. The pytest-selenium user can either override the fixture (but don't decorate the fixture object since that relies on knowing all the internals of pytest, and I try to treat pytest as a thing I don't want to hack over) or we provide specific hooks like controlling driver initialization. The user once having a live driver, can then use the binding's native hook to control Urllib retries.

**Comment by BeyondEvil** [comment]
Aaaand, you lost me, haha.

I'll ping you on Slack later.
