### ISSUE TITLE
Getting Webdriver version as a metadata

### ISSUE THREAD

**Issue by nitinthukral** [pytest-dev/pytest-selenium#257]
Is there a way we could get the webdriver version as the metadata from pytest-selenium and it could also be added to the HTML report?

**Comment by Dude-X** [comment]
Do you mean the version of the python client library?

**Comment by nitinthukral** [comment]
I mean if I want to know the version of the webdrivers like chromedriver, geckodriver etc. and include it as some metadata either in the logs or the HTML report

**Comment by Dude-X** [comment]
My opinion is that the metadata for your test runner should have something documented, but implementing the code for this would add quite a bit of latency to just run, for example, `chromedriver --version` as a subprocess. It's not difficult to modify the code to add this bit of info, but I am a -1 just because it may be slow to query this info and what if stuff goes wrong like zombie processes, or the process freezes. 

That being said you can always add the code for this using pytest-metadata or pytest-html which lets you add arbitrary stuff.

**Comment by nitinthukral** [comment]
That make sense. I will try using pytest-metadata. However, another question:
Generally using the command "webdriver.Chrome().capabilities['chrome']['chromedriverVersion'].split(' ')[0]" would give us the webdriver version and we do not need to run a subprocess. Could you point me to the method in the pytest-selenium code where this could be implemented, if possible at all?

**Comment by Dude-X** [comment]
If you want to know the version of the Chromedriver in use after instantiating the driver, I would look into the reporting hooks such as the integration with pytest-html. That's off the top of my head. Pytest-metadata reports stuff early in the phase before the driver is initialized.

**Comment by BeyondEvil** [comment]
+1 on using pytest-metadata. It's kind of what it's there for. 😊 

Closing this, but feel free to reopen if you're not satisfied with the answer(s).
