### ISSUE TITLE
Possible to only create a report on failure

### ISSUE THREAD

**Issue by allankilpatrick** [pytest-dev/pytest-selenium#75]
Hi,

Wonder if its possible to only generate a report when a test returns as a failure ?
Had a look at the docs and only see info relating  too `selenium_capture_debug`

thanks

**Comment by davehunt** [comment]
Are you referring to the HTML report? If so, this issue should be logged [here](https://github.com/pytest-dev/pytest-html). That said, if you have no failing tests then you'll simply have a relatively small HTML file generated, which I can't see being an issue. I'm going to close this because I think it's been opened against the wrong repository, but please feel free to reopen with clarifications if I've missed something.
