### ISSUE TITLE
Question: FF/ Chrome unable to bypass self sign SSL certificate

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest-selenium#87]
Hi,

First of all I would like to applogise, because I am not sure this issue is causing by selenium 3 itself or other components issue, please forgive me to spare your time when you reading this.

I have configure selenium 3 in grid setup, then I try to run my existing test script. But my browsers (FF/ Chrome) were unable to bypass self sign SSL certificate error.

However If I configure grid setup with selenium 2.53.1 and my test script just run well.

I have no idea what is the problem and how to fix it. Please share your though if possible, thank you.

Here is my environment setup:
- FF 47.0.1
- pytest 3.0.3
- pytest-selenium 1.5.0
- selenium 3.0.1

**Comment by davehunt** [comment]
This is most likely due to Selenium 3.0 using GeckoDriver and Marionette by default, rather than the legacy Firefox driver. Unfortunately bypassing self-signed certificates is not yet supported by Marionette, although it is being [actively worked on](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196). For now, if you need to test sites with such certificates, you should be able to set the `marionette` capability to `False` to force the use of the legacy Firefox driver. Note that this is not compatible with versions of Firefox later than 47.0.1, so you will need to take care not to upgrade Firefox for now.
