### ISSUE TITLE
Setting firefox-profile in conftest

### ISSUE THREAD

**Issue by fspinillo** [pytest-dev/pytest-selenium#95]
I'm currently setting the profile via command line with --firefox-profile=PATH, but am wondering if it is possible to do so with a fixture. I was looking through the codebase and saw --firefox-path is set via firefox-profile in pytest_selenium.py. I also saw this ticket relating to defining preferences https://github.com/pytest-dev/pytest-selenium/issues/86

So I set up my fixture like so, but it seems to not use the correct profile

```
@pytest.fixture
def firefox_profile(firefox_profile):
    firefox_profile = '[PATH]'
    return firefox_profile
```

Edit: So it turns out the set up I have in conftest works fine, the issue is being caused by an additional pytest_addoption I'm passing through.

**Comment by davehunt** [comment]
These fixtures are not currently documented, which I should fix. It's actually a better way to specify a profile than using the command line. The important thing to note is that `firefox_profile` in this case is a `FirefoxProfile` object, and if you don't need to modify that, then you don't need to include it in the method signature of your fixture. Here are a few ideas to try, and if you're interested in helping to improve the docs, that would be awesome:

```python
@pytest.fixture
def firefox_profile():
    return '[PATH]'
```

This should work, because if the profile is a string, then a new `FirefoxProfile` object should be created from it. Alternatively, you could try:

```python
from selenium.webdriver import FirefoxProfile

@pytest.fixture
def firefox_profile():
    return FirefoxProfile('[PATH]')
```

**Comment by fspinillo** [comment]
Thanks @davehunt those work as well. The issue I'm running into has to do with my own pytest_addoption I'm calling for handling production vs branch urls. I noticed pytest-selenium has a plugin for just this feature so I'm working on converting over to that.
